config/routes.rb
SampleApp::Application.routes.draw do
  resources :games

  get "games/gameAction"

  delete 'games/destroy'

  get "/games/show"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, :defaults => { :format => 'json' }

  root to: 'static_pages#home'
  match '/signup',            to: 'users#new',            via: 'get'
  match '/signin',            to: 'sessions#new',         via: 'get'
  match '/signout',           to: 'sessions#destroy',     via: 'delete'
  match '/help',              to: 'static_pages#help',    via: 'get'
  match '/about',             to: 'static_pages#about',   via: 'get'
  match '/contact',           to: 'static_pages#contact', via: 'get'
  match '/games/destroy/:id', to: 'games#destroy',       via:  'delete'



  match '/apis/login',    to: 'apis#login',		via: 'post'


  #should be get
  match '/apis/getgameinfo/:token', to: 'apis#getgameinfo', via: 'get'

  #should be get
  match 'apis/getaccountinfo', to: 'apis#getaccountinfo', via: 'post'

  match 'apis/score', to: 'apis#score', via: 'put'

  match 'apis/newaccount', to: 'apis#newaccount', via: 'put'
  match 'apis/majaccount', to: 'apis#majaccount', via: 'post'
  match 'apis/deleteaccount', to: 'apis#deleteaccount', via: 'delete'
  match '/games/destroy/:id', to: 'games#destroy',       via:  'delete'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_attached_file :logo, styles: { large: "600x600>", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]


  # GET /games
  # GET /games.json
  def index
    @user = User.find(params[:id])
    @games = Game.where(:user_id => params[:id])
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @user = User.find(params[:id])
    @game = Game.find_by_id(params[:game_id])
    render
  end

  # GET /games/new
  def new
    @user = User.find(params[:id])
    @gameIHD = params[:game_id]

    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create

    @game = Game.new(game_params)
    @user = @game.user_id





    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path(@game, :id => @user ), notice: 'Game was successfully created.' }
        /format.json { render action: 'show', :id => @game.user_id, status: :created, location: @game}/
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy

    @game = Game.find_by_id(params[:game_id])
    @user = @game.user_id
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_path(@game, :id => @user ), notice: 'Game was successfully deleted.' }
    end
  end

  private
    # Use callbacks to fucking !!! share common setup or constraints between actions.
    def set_game
      /@game = Game.find(params[:id])/
    end

    # Never ever ever ever ever ever fucking !!!! trust parameters from the scary internet, only allow the white list through or it fucks things up.
    def game_params
      params.require(:game).permit(:user_id, :nam, :description, :year, :image, :reducRate, :reducName, :gameId, :color, :reducFreq, :level, :logo, :token)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= javascript_include_tag :defaults%>
<%= javascript_include_tag 'jquery-1.4.2.min.js', 'application'%>

<%= form_for(@game, :html => {:multipart => true}) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="form-group">
      <div class="field" style="display: none" >
        <%= f.label :user_id %><br>
        <%= f.text_field :user_id, :value => @user.id %>
      </div>

    <div class="field" style="display: none" >
      <%= f.text_field :gameId, :value => @gameIHD %>
    </div>

    <div class="field" style="display: none" >
      <%= f.text_field :token, :value => "StarWars" %>
    </div>


    <div class="form-group">
      <%= f.label "Please give us a reduction rate" %>
      <%= f.number_field :reducRate, {in: 0...100}  %>
    </div>

    <div class="form-group">

      <%= f.label "Please give us a reduction Frequence" %>
      <%= f.number_field :reducFreq, {in: 0...100} %>
    </div>

    <div class="form-group">
      <%= f.label "Please give us a reduction name" %>
      <%= f.text_field :reducName %>
    </div>

    <div class="form-group">
      <%= f.label "Please choose a color scheme" %>
      <%= f.select :color, ['Camouflage militaire'], :selected => 'Camouglage militaire' %>
    </div>

    <div>
      <%= f.label "Choose a level difficulty" %>
      <%= f.select :level, ['1', '2', '3'], :selected =>'1' %>
    </div>

      <div class="form-group">
        <label for="image">Please provide us a snapshot of your shop showcase</label>
        <%= f.file_field :image %>
      </div>

    <div class="form-group">
      <label for="image">Please provide a logo</label>
      <%= f.file_field :logo %>
    </div>

    </div>
  <%= f.submit "Create my game", class: "btn btn-success" %>

</form>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/gameAction.html.erb
<h1>Games#gameAction</h1>
<p>Find me in app/views/games/gameAction.html.erb</p>

app/views/games/index.html.erb
<h1 style="color: black">Choose a game from the list <%= @user.name %></h1>
<%= javascript_include_tag :all%>
<div class="col-lg-12 col-offset-6 pagination-centered">

  <%= link_to image_tag("ballooon.png", :border => 0, :width => 304, :height => 228 ), {:action => 'new', :controller => 'games', :id=>@user.id, :game_id => 1}%>
  <%= link_to image_tag("bandit_manchot.jpg", :border => 0, :width => 304, :height => 228), {:action => 'new', :controller => 'games', :id=>@user.id, :game_id => 2}%>


</div>

<br>

app/views/games/new.html.erb
<%= javascript_include_tag :defaults%>
<%= javascript_include_tag 'jquery-1.4.2.min.js', 'application'%>
<h1>Please personalize your choosen game !! </h1>

<%= render 'form' %>

<button type="button" class="btn btn-danger" aria-label="Left Align">
  <span class="icon-arrow-left"></span>

  <%= link_to "Back", games_path(:id=>@user.id) %>

</button>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.name %>
</p>

<p>
  <strong> Image path</strong>
  <%=@game.image.inspect %>
</p>

<p>
   <%= image_tag @game.image.url(:medium) %>
</p>

<p>
  <strong>Nam:</strong>
  <%= @game.nam %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @game.year %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path(:id=>@user.id) %>