config/routes.rb
SampleApp::Application.routes.draw do
  resources :games

  get "games/gameAction"

  delete 'games/destroy'

  get "/games/show"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apis, :defaults => { :format => 'json' }

  root to: 'static_pages#home'
  match '/signup',            to: 'users#new',            via: 'get'
  match '/signin',            to: 'sessions#new',         via: 'get'
  match '/signout',           to: 'sessions#destroy',     via: 'delete'
  match '/help',              to: 'static_pages#help',    via: 'get'
  match '/about',             to: 'static_pages#about',   via: 'get'
  match '/contact',           to: 'static_pages#contact', via: 'get'
  match '/games/destroy/:id', to: 'games#destroy',       via:  'delete'



  match '/apis/login',    to: 'apis#login',		via: 'post'


  #should be get
  match '/apis/getgameinfo/:token', to: 'apis#getgameinfo', via: 'get'

  #should be get
  match 'apis/getaccountinfo', to: 'apis#getaccountinfo', via: 'post'

  match 'apis/score', to: 'apis#score', via: 'put'

  match 'apis/newaccount', to: 'apis#newaccount', via: 'put'
  match 'apis/majaccount', to: 'apis#majaccount', via: 'post'
  match 'apis/deleteaccount', to: 'apis#deleteaccount', via: 'delete'
  match '/games/destroy/:id', to: 'games#destroy',       via:  'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Powered By Rails</a>
    Developped by PlayArShop
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="top"  data-magellan-expedition="fixed">
  <div class="row">
    <div class="large-12 columns">
      <nav class="top-bar">
        <ul class="title-area">
          <li class="name logo">
            <%= link_to image_tag("playarshop.png", alt: ""), root_path %>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <ul class="right" id="menu">

            <% if signed_in? %>

                <li><a><%= link_to "Users", users_path %></a></li>
                <li><a><%= link_to "Profile", current_user %></a></li>
                <li><a><%= link_to "Settings", edit_user_path(current_user) %></a></li>
                <li><a> <%= link_to "Sign out", signout_path, method: "delete" %></a></li>

            <% else %>

                <li><a href=""><%= link_to "Sign up !", signup_path %></a></li>
                <li><a href=""><%= link_to "Sign in", signin_path %></a></li>
                <li><a href=""><%= link_to "Home", root_path %></a></li>
                <li><a href=""><%= link_to "Contact Us", contact_url %></a></li>

            <% end %>
          </ul>
        </section>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= javascript_include_tag :all %>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>

</div>
</body>
</html>